config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: "registrations" }
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :stories, only: [:new, :create, :index, :show, :edit]
  root "stories#index"
end

app/models/application_record.rb
# rubocop:disable Layout/EndOfLine

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

# rubocop:enable Layout/EndOfLine

app/models/story.rb
# rubocop:disable Layout/EndOfLine

class Story < ApplicationRecord
  belongs_to :user
end

# rubocop:enable Layout/EndOfLine

app/models/user.rb
# rubocop:disable Layout/EndOfLine

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories
end

# rubocop:enable Layout/EndOfLine

app/controllers/application_controller.rb
# rubocop:disable Layout/EndOfLine

class ApplicationController < ActionController::Base
end

# rubocop:enable Layout/EndOfLine

app/controllers/registrations_controller.rb
# rubocop:disable Layout/EndOfLine

class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

# rubocop:enable Layout/EndOfLine

app/controllers/stories_controller.rb
# rubocop:disable Layout/EndOfLine

class StoriesController < ApplicationController
  before_action :authenticate_user!, only: %i[new create]
  before_action :set_story, only: %i[show]

  # GET /stories or /stories.json
  def index
    @stories = Story.all.order('created_at DESC')
    @story = Story.new
  end

  # GET /stories/1 or /stories/1.json
  def show; end

  # GET /stories/new
  def new
    @story = Story.new
  end

  # GET /stories/1/edit
  def edit; end

  # POST /stories or /stories.json
  def create
    @story = current_user.stories.build(story_params)

    respond_to do |format|
      if @story.save
        format.html { redirect_to @story, notice: 'Story was successfully created.' }
        format.json { render :show, status: :created, location: @story }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stories/1 or /stories/1.json
  def update
    respond_to do |format|
      if @story.update(story_params)
        format.html { redirect_to @story, notice: 'Story was successfully updated.' }
        format.json { render :show, status: :ok, location: @story }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @story.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stories/1 or /stories/1.json
  def destroy
    @story.destroy
    respond_to do |format|
      format.html { redirect_to stories_url, notice: 'Story was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_story
    @story = Story.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def story_params
    params.require(:story).permit(:title, :body)
  end
end

# rubocop:enable Layout/EndOfLine

app/helpers/application_helper.rb
module ApplicationHelper
  def loged_in
    if user_signed_in?
      current_user.username
    else
      'Not logged in'
    end
  end

  def profile_button
    if user_signed_in?
      link_to 'Edit profile', edit_user_registration_path, class: 'navbar-link'
    else
      link_to 'Sign up', new_user_registration_path, class: 'navbar-link'
    end
  end

  def log_out_button
    if user_signed_in?
      link_to 'Logout', destroy_user_session_path, method: :delete, class: 'navbar-link'
    else
      link_to 'Login', new_user_session_path, class: 'navbar-link'
    end
  end
end

app/helpers/stories_helper.rb
# rubocop:disable Style/GuardClause

module StoriesHelper
  def display_name(user)
    user.username = if user_signed_in?
                      user.username
                    else
                      'Anonymous'
                    end
  end

  def display_button(story)
    if user_signed_in? && (current_user.id == story.user.id)
      link_to 'Delete', story, method: :delete, data: { confirm: 'Are you sure?' },
                               class: 'btn btn-danger p-1 text-white'
    end
  end

  def display_new_story_button
    link_to 'New story', new_story_path, class: 'btn bg-dark px-5 py-0 text-white' if user_signed_in?
  end
end

# rubocop:enable Style/GuardClause

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %> 
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <nav class="navbar bg-light">
        <div class="navbar left">
          <h1>Stories</h1>
          </div>
          <div class="navbar right">
              <ul class="nav justify-content-end">
              <li class="nav-item">
                <p class="navbar-text">
            <strong><%= loged_in %></strong>.
            <%= profile_button %> | <%= log_out_button %>
            </p>
            </li>
      </div>
    </nav>
    <div class="d-flex row justify-content-center text-center">
      <%= yield %>
    </div>
  </body>
</html>

app/views/stories/_form.html.erb
<%= form_with(model: story) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stories/edit.html.erb
<div class="row">
    <h2 class="col-12">
        Edit Story
    </h2>
    <div class="col-12">
        <%= render 'form', story: @story %>
    </div>

    <div class="col-12">
        <%= link_to 'Show', @story %> |
        <%= link_to 'Back', stories_path %>
    </div>
</div>

app/views/stories/index.html.erb
<div class="column">
  <div class="title text-center">
    <%= display_new_story_button %>
  </div>
  <div class="row" style="max-width: 1000px">
    <table class="pt-5">
      <tbody>
        <% @stories.each do |story| %>
          <div class="mx-3 my-3 col-5">
            <div class="card" style="width: 400px; height: 200px">
              <div class="card-body">
                <h3 class="card-title text-left">
                  <%= story.title %>
                </h3>
                <p class="card-subtitle mb-2 text-muted text-left">
                  <%= display_name(story.user) %>
                </p>
                <p class="card-text text-left">
                  <%= story.body.truncate(100) %>
                </p>
                <div class="buttons text-left">
                  <%= link_to 'Show', story, class: 'btn bg-secondary text-white p-1' %>
                  <%= display_button(story) %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stories/new.html.erb
<div class="row">
<h2 class="col-12">New Story</h2>

<div class="col-12">
    <%= render 'form', story: @story %>
</div>

<div class="col-12">
    <%= link_to 'Back', stories_path %>
</div>

</div>

app/views/stories/show.html.erb
<div class="row">
  <div class="col-12">
    <h2 class="col-12"><%= @story.title %></h2>
    <p class="col-12 text-muted"><%= display_name(@story.user) %></p>
  </div>

  <p class="col-12">
    <%= @story.body %>
  </p>

  <div class="col-12">
    <%= link_to 'Edit', edit_story_path(@story) %> |
    <%= link_to 'Back', stories_path %>
  </div>

</div>